spring.application.name=job-tracking

spring.datasource.url=jdbc:postgresql://localhost:5432/job_tracking
spring.datasource.username=job_tracking
spring.datasource.password=job_tracking
spring.datasource.driver-class-name=org.postgresql.Driver

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:schema.sql
spring.sql.init.continue-on-error=false
